apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-web{{ include "global.appendTag" . }}
spec:
  selector:
    matchLabels:
      app: blogs-web{{ include "global.appendTag" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: blogs-web{{ include "global.appendTag" . }}
    spec:
      containers:
        - name: blogs-web
          image: dekhor.azurecr.io/blogs-web:{{ .Values.global.revision }}
          ports:
            - containerPort: 80
          env:
            {{- template "global.env" . }}
            - name: REACT_APP_BASE_WEB_PATH
              value: {{ include "blogs-web.rootPath" . | quote }}
            - name: REACT_APP_BASE_SERVER_PATH
              value: {{ include "blogs-server.rootPath" . | quote }}
