apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorms-server{{ include "global.appendTag" . }}
spec:
  selector:
    matchLabels:
      app: dorms-server{{ include "global.appendTag" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: dorms-server{{ include "global.appendTag" . }}
    spec:
      containers:
        - name: dorms-server
          image: dekhor.azurecr.io/dorms-server:{{ .Values.global.revision }}
          ports:
            - containerPort: 4003
          env:
            {{- template "global.env" . }}
            - name: BASE_WEB_PATH
              value: {{ include "dorms-web.rootPath" . | quote }}
            - name: BASE_SERVER_PATH
              value: {{ include "dorms-server.rootPath" . | quote }}
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-credential
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-credential
                  key: SUPABASE_KEY
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-credential
                  key: SUPABASE_JWT_SECRET


